#!/usr/bin/env bash
# rpi-voice-agent / setup.sh
# =============================================================
# Raspberry Pi 5 (Raspberry Pi OS Bookworm 64-bit) 向け
# ゼロから全コンポーネントを自動セットアップするスクリプト
#
# 使い方:
#   git clone https://github.com/YOUR_USER/rpi-voice-agent.git
#   cd rpi-voice-agent
#   cp .env.example .env        # ← 認証情報を編集
#   bash setup.sh
# =============================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[setup]${NC} $*"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $*"; }
err()  { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }
step() { echo -e "\n${CYAN}━━━ $* ━━━${NC}"; }

# ─── 前提チェック ─────────────────────────────
step "Checking prerequisites"

[[ "$(uname -m)" == "aarch64" ]] || err "This script is for arm64 (Raspberry Pi 5). Current arch: $(uname -m)"
[[ -f ".env" ]]                  || err ".env file not found. Run: cp .env.example .env  and fill in the values."

source .env

[[ -z "${HERMES_API_KEY:-}" || "${HERMES_API_KEY}" == "your-strong-api-key-here" ]] \
  && err "HERMES_API_KEY is not set in .env. Generate one with: openssl rand -hex 32"

[[ -z "${HA_PASSWORD:-}" || "${HA_PASSWORD}" == "your-ha-password-here" ]] \
  && err "HA_PASSWORD is not set in .env. Set a secure password for the HA admin account."

log "Prerequisites OK"

# ─── 1. システムパッケージ更新 ─────────────────
step "Updating system packages"
sudo apt-get update -qq
sudo apt-get install -y -qq \
  curl \
  git \
  ca-certificates \
  gnupg \
  lsb-release \
  netcat-openbsd \
  avahi-daemon \
  jq

# ─── 2. Docker インストール（未インストールの場合） ──
step "Installing Docker"
if command -v docker &>/dev/null; then
  log "Docker already installed: $(docker --version)"
else
  log "Installing Docker via official script..."
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  warn "Docker group added. You may need to log out and back in."
  warn "If docker commands fail, run: newgrp docker"
fi

# Docker Compose プラグイン確認
if ! docker compose version &>/dev/null; then
  log "Installing docker-compose-plugin..."
  sudo apt-get install -y -qq docker-compose-plugin
fi
log "Docker Compose: $(docker compose version --short)"

# ─── 3. 音声デバイス確認 ────────────────────────
step "Checking audio devices"
if aplay -l 2>/dev/null | grep -q "card"; then
  log "Audio output device found:"
  aplay -l 2>/dev/null | grep "^card" | head -5
else
  warn "No audio output device found. TTS playback will not work without a speaker."
fi

if arecord -l 2>/dev/null | grep -q "card"; then
  log "Audio input (microphone) found:"
  arecord -l 2>/dev/null | grep "^card" | head -5
else
  warn "No microphone found. Wake word detection requires a USB microphone."
fi

# ─── 4. HA 設定ファイルを初期化 ─────────────────
step "Initializing Home Assistant config"
mkdir -p config/homeassistant

if [[ ! -f config/homeassistant/configuration.yaml ]]; then
  log "Creating initial configuration.yaml..."
  cat > config/homeassistant/configuration.yaml << 'HACFG'
# Home Assistant Core configuration
# Generated by rpi-voice-agent setup.sh

homeassistant:
  name: "RPi Voice Agent"
  latitude: 35.6762
  longitude: 139.6503
  elevation: 0
  unit_system: metric
  currency: JPY
  country: JP
  language: ja
  time_zone: Asia/Tokyo

# 基本コンポーネント
default_config:

# ロギング
logger:
  default: warning
  logs:
    homeassistant.components.wyoming: info
    homeassistant.components.assist_pipeline: info
HACFG
  log "configuration.yaml created"
else
  log "configuration.yaml already exists, skipping"
fi

# ─── 5. openWakeWord カスタムモデルディレクトリ ──
step "Setting up openWakeWord directories"
mkdir -p config/openwakeword/custom_models
log "Custom wake word models directory: config/openwakeword/custom_models/"
log "Place .tflite model files here to use custom wake words."

# ─── 6. Hermes 設定ディレクトリ ─────────────────
step "Setting up Hermes config directory"
mkdir -p config/hermes

# ─── 7. Docker イメージを事前取得 ───────────────
step "Pulling Docker images (this may take several minutes on Pi 5)"
docker compose pull

# ─── 8. スタック起動 ────────────────────────────
step "Starting all services"
docker compose up -d

log "Waiting for services to start..."
sleep 15

# ─── 9. ヘルスチェック ──────────────────────────
step "Health checks"
check_service() {
  local name="$1"
  local url="$2"
  local max_wait="${3:-120}"
  local elapsed=0
  local interval=5

  echo -n "  Waiting for ${name}..."
  while ! curl -sf "$url" > /dev/null 2>&1; do
    sleep $interval
    elapsed=$((elapsed + interval))
    echo -n "."
    if [[ $elapsed -ge $max_wait ]]; then
      echo " TIMEOUT"
      warn "${name} did not respond within ${max_wait}s. Check: docker compose logs ${name}"
      return 1
    fi
  done
  echo " OK (${elapsed}s)"
}

check_service "ollama"       "http://localhost:11434/api/tags"  120
check_service "homeassistant" "http://localhost:8123/"           180
check_service "hermes"       "http://localhost:8642/health"     120

# openwakeword は HTTP エンドポイントがないので nc で確認
echo -n "  Waiting for openwakeword (TCP:10400)..."
elapsed=0
while ! nc -z localhost 10400 2>/dev/null; do
  sleep 5; elapsed=$((elapsed + 5)); echo -n "."
  [[ $elapsed -ge 60 ]] && { echo " TIMEOUT"; break; }
done
[[ $elapsed -lt 60 ]] && echo " OK" || warn "openwakeword may not be ready"

# ─── 10. HA 自動セットアップ ────────────────────────
step "Running Home Assistant automated setup"
bash "$(dirname "$0")/scripts/ha-setup.sh"

# ─── 11. 完了メッセージ ─────────────────────────
PI_IP=$(hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║          rpi-voice-agent setup complete!             ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Home Assistant  → ${CYAN}http://${PI_IP}:8123${NC}"
echo -e "  Ollama API      → ${CYAN}http://${PI_IP}:11434${NC}"
echo -e "  Hermes Agent    → ${CYAN}http://${PI_IP}:8642${NC}"
echo -e "  Wake Word       → ${YELLOW}${WAKE_WORD:-ok_nabu}${NC} (TCP port 10400)"
echo ""
echo -e "  Remaining manual step:"
echo -e "  Open ${CYAN}http://${PI_IP}:8123${NC} → Settings → Voice Assistants → Add Assistant"
echo -e "    Wake Word Engine : openWakeWord → ${YELLOW}${WAKE_WORD:-ok_nabu}${NC}"
echo -e "    Speech-to-text   : Faster Whisper"
echo -e "    Text-to-speech   : Piper"
echo ""
echo -e "  Useful commands:"
echo -e "  ${CYAN}docker compose logs -f${NC}               # tail all logs"
echo -e "  ${CYAN}docker compose logs -f hermes${NC}        # tail Hermes only"
echo -e "  ${CYAN}docker compose restart hermes${NC}         # restart Hermes"
echo -e "  ${CYAN}bash pull-model.sh qwen2.5:3b${NC}  # pull a model"
echo ""
